# Generated by Django 5.2.7 on 2025-11-03 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('qtd_minima', models.IntegerField()),
                ('qtd_produto', models.IntegerField()),
                ('tipo_produto', models.CharField(max_length=20)),
                ('tensao', models.CharField(max_length=10)),
                ('dimensao', models.CharField(max_length=15)),
                ('resolucao_tela', models.CharField(max_length=15)),
                ('armazenamento_gb', models.IntegerField()),
                ('conectividade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('DELETAR', 'Produto deletado'), ('AUMENTAR', 'Produto adicionado ao estoque'), ('RETIRADO', 'Produto retirado do estoque'), ('ADICIONAR', 'Novo produto')], max_length=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('id_estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.estoque')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
