# Generated by Django 5.2.7 on 2025-11-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_historico_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='acao',
            field=models.CharField(choices=[('DELETAR', 'Produto deletado'), ('ENTRADA_PRODUTO', 'Produto adicionado ao estoque'), ('SAIDA_PRODUTO', 'Produto retirado do estoque'), ('NOVO_PRODUTO', 'Novo produto')], max_length=20),
        ),
    ]
