# Generated by Django 5.2.7 on 2025-11-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_historico_acao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='tipo_produto',
            field=models.CharField(choices=[('smartphone', 'Celular'), ('notebook', 'Notebook'), ('smart_tv', 'Smart TV')], max_length=20),
        ),
    ]
